---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Inventory Manager ElasticBeanstalk application template.'

Resources:

  InventoryManager:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: Inventory Manager
      Description: OneView Inventory Manager
    # Important
    # If you specify a name, you cannot perform updates that require replacement of this resource.

Outputs:
  InventoryManagerApplication:
    Description: 'Inventory Manager Application'
    Value: !Ref InventoryManager
    Export:
      Name: !Sub InventoryManagerApplication
