---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network: Primary VPN Configuration to a Customer Gateway.'
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  CustomerGatewayABGPAsn:
    Description: 'The stomer Gateway As BGP ASN.'
    Type: Number
  CustomerGatewayAIP:
    Description: 'Customer Gateway A IP Address.'
    Type: String
    AllowedPattern: '^((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?)'
    ConstraintDescription: 'Must be a valid IP address.'
  CustomerGatewayAName:
    Description: 'Customer Gateway A Name.'
    Type: String
  CustomerGatewayBBGPAsn:
    Description: 'The Customer Gateway Bs BGP ASN.'
    Type: Number
  CustomerGatewayBIP:
    Description: 'Customer Gateway B IP Address.'
    Type: String
    AllowedPattern: '^((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?)'
    ConstraintDescription: 'Must be a valid IP address.'
  CustomerGatewayBName:
    Description: 'Customer Gateway B Name.'
    Type: String
  RoutePropagation:
    Description: 'Boolean indicating whether route propagation should be used.'
    Default: true
    Type: String
    AllowedValues:
      - true
      - false

Conditions:
  RoutePropagationBoolean: !Equals [ !Ref RoutePropagation, true ]

Resources:

  VPNGateway:
    #Virtual Private Gateway
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
      - Key: Name
        Value: !Sub '${ParentVPCStack}-VPNGateway'
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

  AttachVpnGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: VPNGateway
    Properties:
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      VpnGatewayId: !Ref VPNGateway

  VPNGatewayRoutePropagation:
    Type: AWS::EC2::VPNGatewayRoutePropagation
    Condition: RoutePropagationBoolean
    DependsOn: VPNGateway
    Properties:
      RouteTableIds:
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-RouteTablePublic'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-RouteTablePrivateA'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-RouteTablePrivateB'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-RouteTablePrivateC'
      VpnGatewayId: !Ref VPNGateway

  CustomerGatewayA:
    Type: AWS::EC2::CustomerGateway
    Properties:
      Type: ipsec.1
      BgpAsn: !Ref CustomerGatewayABGPAsn
      IpAddress: !Ref CustomerGatewayAIP
      Tags:
      - Key: Name
        Value: !Ref CustomerGatewayAName
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

  CustomerGatewayB:
    Type: AWS::EC2::CustomerGateway
    Properties:
      Type: ipsec.1
      BgpAsn: !Ref CustomerGatewayBBGPAsn
      IpAddress: !Ref CustomerGatewayBIP
      Tags:
      - Key: Name
        Value: !Ref CustomerGatewayBName
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

  VPNConnection1:
    Type: AWS::EC2::VPNConnection
    DependsOn: VPNGateway
    Properties:
      Type: ipsec.1
      CustomerGatewayId: !Ref CustomerGatewayA
      VpnGatewayId: !Ref VPNGateway
      Tags:
      - Key: Name
        Value: Inspect-PaloAlto-w2a
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

  VPNConnection2:
    Type: AWS::EC2::VPNConnection
    DependsOn: VPNGateway
    Properties:
      Type: ipsec.1
      CustomerGatewayId: !Ref CustomerGatewayB
      VpnGatewayId: !Ref VPNGateway
      Tags:
      - Key: Name
        Value: Inspect-PaloAlto-w2b
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

Outputs:
  VPNGateway:
    Description: VPN Gateway
    Value: !Ref VPNGateway
    Export:
      Name: !Sub '${ParentVPCStack}-VPNGateway'
