---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network: Primary VPN Configuration to a Customer Gateway.'
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String

Resources:

  VPNGateway:
    #Virtual Private Gateway
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
      - Key: Name
        Value: !Sub '${ParentVPCStack}-VPNGateway'
      - Key: Project
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-ProjectName'
      - Key: LiveIdentifier
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-LiveIdentifier'

  AttachVpnGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: VPNGateway
    Properties:
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      VpnGatewayId: !Ref VPNGateway
