---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security group configuration for OneView Commerce POS Server'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parent Stack'
      Parameters:
      - ParentVPCStack
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  FQDNName:
    Description: 'The fully qualified domain name for the directory. This will be prepended by ad. to not conflict with Route53 Zones.'
    Type: String
  ADSize:
    Description: 'The size for the AD directory. Only Small and Large are allowed.'
    Type: String
    AllowedValues:
    - Small
    - Large
    Default: Small
  SimpleADPW:
    Description: 'The administration password to set for the Simple AD server.'
    Type: String
    NoEcho: true
    AllowedPattern: (?=.{9,})(?=.*?[^\w\s])(?=.*?[0-9])(?=.*?[A-Z]).*?[a-z].*
Conditions:
  IsProduction: !Equals [ !Sub '${ParentVPCStack}-LiveIdentifier', production ]

Resources:

  SimpleAD:
    Type: "AWS::DirectoryService::SimpleAD"
    Properties:
      Name: !Sub 'ad.${FQDNName}'
      Password:
        Ref: SimpleADPW
      Size: !Ref ADSize
      VpcSettings:
        SubnetIds:
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPublic'
        VpcId:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
