AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parent Stack'
      Parameters:
      - ParentVPCStack
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  MinASGSize:
    Description: 'Minimum number of instances running'
    Type: Number
    Default: 1
  MaxASGSize:
    Description: 'Maximum number of instances running'
    Type: Number
    Default: 3
  HostedZoneId:
    Description: 'The Hosted Zone ID used to create Record Sets (URLs)'
    Type: String
  HostedZoneDomainName:
    Description: 'The Domain Name with extension used to create Record Sets (URLs). eg: ovcdemo.com'
    Type: String
  SolutionStackName:
    Description: 'The solution stack used'
    Type: String
    Default: '64bit Amazon Linux 2016.09 v2.5.0 running Multi-container Docker 1.12.6 (Generic)'

Resources:

  PromotionEngine:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: OneView Promotion Engine
    # Important
    # If you specify a name, you cannot perform updates that require replacement of this resource.

  PromotionEngineConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: PromotionEngine
      Description: Promotion Engine Configuration Template
      OptionSettings:

      # Scaling Settings
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: !Ref MinASGSize
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: !Ref MaxASGSize
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced

      # VPC Network Settings
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'
      - Namespace: aws:ec2:vpc
        OptionName: AssociatePublicIpAddress
        Value: true

      # Settings
      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-PromotionEngineSecurityGroup'

      SolutionStackName: !Ref SolutionStackName

Outputs:
  PromotionEngineApplication:
    Description: 'Promotion Engine Application'
    Value: !Ref PromotionEngine
    Export:
      Name: !Sub '${ParentVPCStack}-PromotionEngineApplication'
  PromotionEngineConfigurationTemplate:
    Description: 'Promotion Engine Configuration Template'
    Value: !Ref PromotionEngineConfigurationTemplate
    Export:
      Name: !Sub '${ParentVPCStack}-PromotionEngineConfigurationTemplate'
  HostedZone:
    Description: 'Promotion Engine Hosted Zone'
    Value: !Ref HostedZoneId
    Export:
      Name: !Sub '${ParentVPCStack}-PromotionEngineHostedZoneId'
  HostedZoneDomainName:
    Description: 'Promotion Engine Domain Name'
    Value: !Ref HostedZoneDomainName
    Export:
      Name: !Sub '${ParentVPCStack}-PromotionEngineHostedZoneDomainName'
