AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parent Stack'
      Parameters:
      - ParentVPCStack
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String

Resources:

  PromotionEngine:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: Promotion Engine
      Description: OneView Promotion Engine
    # Important
    # If you specify a name, you cannot perform updates that require replacement of this resource.

Outputs:
  PromotionEngineApplication:
    Description: 'Promotion Engine Application'
    Value: !Ref PromotionEngine
    Export:
      Name: PromotionEngineApplication
