---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Promotion Engine ElasticBeanstalk application template.'

Resources:

  PromotionEngine:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: Promotion Engine
      Description: OneView Promotion Engine
    # Important
    # If you specify a name, you cannot perform updates that require replacement of this resource.

Outputs:
  PromotionEngineApplication:
    Description: 'Promotion Engine Application'
    Value: !Ref PromotionEngine
    Export:
      Name: PromotionEngineApplication
